version: '2'
services:
  javascript:
    image: "antham/cvqld-javascript"
    build:
      context: front/javascript
  stylesheet:
    image: "antham/cvqld-stylesheet"
    build:
      context: front/stylesheet
  server:
    image: "antham/cvqld-server"
    build:
      context: server
    depends_on:
      - javascript
      - stylesheet
  api:
    image: "antham/cvqld-api"
    build:
      context: api
