version: '2'
services:
  app:
    build: .
    env_file: .env
    restart: always
    command: askme_linux_amd64
  database:
    build:
      context: .
      dockerfile: Dockerfile-database
    ports:
      - "5432"
    env_file: .env
