version: '2'
services:
  server:
    image: "antham/askme-pub"
    env_file: .env
    ports:
      - "80:80"
  app:
    image: "antham/askme"
    env_file: .env
    restart: always
    command: askme_linux_amd64
  database:
    env_file: .env
    image: "antham/askme-database"
    ports:
      - "5432"
