version: '2'
services:
  server:
    image: "antham/cqlvd-server"
    env_file: .env
    restart: always
    ports:
      - "80:80"
    depends_on:
      - "api"
  api:
    image: "antham/cqlvd-api"
    env_file: .env
    restart: always
    depends_on:
      - "database"
  database:
    image: "postgres"
    env_file: .env
    restart: always
    ports:
      - "5432"
