version: '2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-public
    ports:
      - "80:80"
  app:
    build: .
    env_file: .env
  postgres:
    image: postgres
    ports:
      - "5432"
