FROM alpine:3.6

RUN apk add --no-cache ca-certificates nginx && \
    mkdir /run/nginx && \
    adduser -H -D -G www-data www-data

COPY public /public/
COPY nginx/nginx.conf /etc/nginx/

CMD ["/usr/sbin/nginx", "-c", "/etc/nginx/nginx.conf"]
