version: '2'
services:
  server:
    image: "antham/askme-pub"
    ports:
      - "80:80"
  app:
    env_file: .env
    image: "antham/askme"
    restart: always
    command: askme_linux_amd64
  postgres:
    image: postgres
    ports:
      - "5432"
